/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerCliente;
import controller.ControllerItensVenda;
import controller.ControllerItensVendaProduto;
import controller.ControllerProduto;
import controller.ControllerVendaCli;
import controller.ControllerVenda;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ModelCliente;
import model.ModelItensVenda;
import model.ModelItensVendaProduto;
import model.ModelProduto;
import model.ModelVenda;
import model.ModelvendaCli;
import utilitario.ViewUtili;

/**
 *
 * @author AurelioTEC
 */
public class ViewVenda extends javax.swing.JFrame {

    ArrayList<ModelCliente> listaCliente = new ArrayList<>();
    ArrayList<ModelProduto> listaProduto = new ArrayList<>();
    ArrayList<ModelvendaCli> listaCli = new ArrayList<>();
    ArrayList<ModelItensVenda> listaIV = new ArrayList<>();
    ArrayList<ModelItensVendaProduto> listaIVP = new ArrayList<>();
    ControllerProduto cp = new ControllerProduto();
    ControllerVendaCli cvc = new ControllerVendaCli();
    ControllerVenda cv = new ControllerVenda();
    ControllerItensVenda civ = new ControllerItensVenda();
    ControllerCliente cc = new ControllerCliente();
    ControllerItensVendaProduto cIVP = new ControllerItensVendaProduto();
    ModelCliente mdc = new ModelCliente();
    ModelProduto mp = new ModelProduto();
    ModelItensVenda miv = new ModelItensVenda();
    ModelVenda mv = new ModelVenda();
    ModelItensVendaProduto mIVP = new ModelItensVendaProduto();
    String dataf, alterarSalvar;

    /**
     * Creates new form ViewVenda
     */
    public ViewVenda() {
        initComponents();
        setLocationRelativeTo(null);
        carregarVenda();
        Date data = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        dataf = formato.format(data);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MPProduto = new javax.swing.JPopupMenu();
        MPRemover = new javax.swing.JMenuItem();
        TPVenda = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        TxtCodClie = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtCodVenda = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtCodProd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BtnAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbProduto = new javax.swing.JTable();
        BtnNovo = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        BtnSalvar = new javax.swing.JButton();
        TxtDesconto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TxtQtd = new javax.swing.JFormattedTextField();
        TxtValotTotal = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        CbProduto = new componentes.UJComboBox();
        CbNomeCli = new componentes.UJComboBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TbVenda = new javax.swing.JTable();
        TxtPesquisar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        BtnPesquisar = new javax.swing.JButton();
        BtnAlterar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        BtnImprimir = new javax.swing.JButton();

        MPRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/delete_18px.png"))); // NOI18N
        MPRemover.setText("Eliminar Item");
        MPRemover.setActionCommand("");
        MPRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MPRemoverActionPerformed(evt);
            }
        });
        MPProduto.add(MPRemover);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        TxtCodClie.setEnabled(false);
        TxtCodClie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TxtCodClieMouseExited(evt);
            }
        });

        jLabel1.setText("Cod. do Cliente");

        jLabel2.setText("Nome do Cliente");

        TxtCodVenda.setEditable(false);

        jLabel3.setText("Codigo da Venda");

        TxtCodProd.setEnabled(false);
        TxtCodProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TxtCodProdMouseExited(evt);
            }
        });

        jLabel4.setText("Cod. do Produto");

        jLabel5.setText("Nome do Cliente");

        jLabel6.setText("Qtd.");

        BtnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/add_18px.png"))); // NOI18N
        BtnAdd.setText("ADD");
        BtnAdd.setEnabled(false);
        BtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddActionPerformed(evt);
            }
        });

        TbProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód. Prod", "Nome Produto", "Qtd.", "Valor Unt.", "Valor Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbProduto.setComponentPopupMenu(MPProduto);
        TbProduto.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(TbProduto);
        if (TbProduto.getColumnModel().getColumnCount() > 0) {
            TbProduto.getColumnModel().getColumn(1).setMinWidth(240);
            TbProduto.getColumnModel().getColumn(1).setPreferredWidth(240);
            TbProduto.getColumnModel().getColumn(2).setMinWidth(70);
            TbProduto.getColumnModel().getColumn(2).setPreferredWidth(70);
        }

        BtnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/file_18px.png"))); // NOI18N
        BtnNovo.setText("Novo");
        BtnNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNovoActionPerformed(evt);
            }
        });

        BtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/cancel_18px.png"))); // NOI18N
        BtnCancelar.setText("Cancelar");
        BtnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnCancelar.setEnabled(false);
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        BtnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/save_18px.png"))); // NOI18N
        BtnSalvar.setText("Salvar");
        BtnSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnSalvar.setEnabled(false);
        BtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalvarActionPerformed(evt);
            }
        });

        TxtDesconto.setEnabled(false);
        TxtDesconto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtDescontoFocusLost(evt);
            }
        });
        TxtDesconto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TxtDescontoMouseExited(evt);
            }
        });
        TxtDesconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDescontoActionPerformed(evt);
            }
        });

        jLabel7.setText("Valor Total");

        jLabel8.setText("Desconto:");

        TxtQtd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        TxtQtd.setEnabled(false);
        TxtQtd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TxtQtdMouseExited(evt);
            }
        });

        TxtValotTotal.setEditable(false);
        TxtValotTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("######0.## "))));

        jLabel10.setText("%");

        CbProduto.setAutocompletar(true);
        CbProduto.setEnabled(false);
        CbProduto.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                CbProdutoPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        CbNomeCli.setAutocompletar(true);
        CbNomeCli.setEnabled(false);
        CbNomeCli.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                CbNomeCliPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                    .addComponent(TxtCodClie))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CbNomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtCodVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TxtCodProd))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(CbProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                    .addComponent(TxtQtd))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BtnNovo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnSalvar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(TxtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10))
                                    .addComponent(jLabel8))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7)
                                    .addComponent(TxtValotTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtCodClie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtCodVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbNomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtCodProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAdd)
                    .addComponent(TxtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtValotTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TxtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCancelar)
                    .addComponent(BtnNovo)
                    .addComponent(BtnSalvar))
                .addGap(14, 14, 14))
        );

        TPVenda.addTab("Cadastrar", jPanel1);

        TbVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Data"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbVendaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TbVenda);
        if (TbVenda.getColumnModel().getColumnCount() > 0) {
            TbVenda.getColumnModel().getColumn(0).setMinWidth(100);
            TbVenda.getColumnModel().getColumn(0).setPreferredWidth(100);
            TbVenda.getColumnModel().getColumn(0).setMaxWidth(100);
            TbVenda.getColumnModel().getColumn(2).setMinWidth(100);
            TbVenda.getColumnModel().getColumn(2).setPreferredWidth(100);
            TbVenda.getColumnModel().getColumn(2).setMaxWidth(100);
        }

        jLabel9.setText("Pesquisar");

        BtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/search_18px.png"))); // NOI18N
        BtnPesquisar.setText("Pesquisar");

        BtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/edit_18px.png"))); // NOI18N
        BtnAlterar.setText("Alterar");
        BtnAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAlterar.setEnabled(false);
        BtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAlterarActionPerformed(evt);
            }
        });

        BtnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/delete_18px.png"))); // NOI18N
        BtnEliminar.setText("Eliminar");
        BtnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnEliminar.setEnabled(false);
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        BtnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/print_18px.png"))); // NOI18N
        BtnImprimir.setText("Imprimir");
        BtnImprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(TxtPesquisar)
                                .addGap(18, 18, 18)
                                .addComponent(BtnPesquisar))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(BtnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnImprimir)
                        .addGap(14, 14, 14))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnEliminar)
                    .addComponent(BtnAlterar)
                    .addComponent(BtnImprimir))
                .addContainerGap())
        );

        TPVenda.addTab("Mostrar/Editar/Eliminar", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TPVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TPVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNovoActionPerformed
        alterarSalvar = "salvar";
        this.limparCampos();
        BtnCancelar.setEnabled(true);
        btnNovo();
        this.listarCliente();
        this.listarProduto();
        this.carregarComboCliente();
        this.carregarComboProduto();
    }//GEN-LAST:event_BtnNovoActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        BtnNovo.setEnabled(true);
        BtnCancelar.setEnabled(false);
        this.limparCampos();
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void BtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvarActionPerformed
        double soma = 0, valor;
        int codigoVenda = 0;
        listaIV = new ArrayList<>();
        int cont = TbProduto.getRowCount();
        for (int i = 0; i < cont; i++) {
            valor = (double) TbProduto.getValueAt(i, 4);
            soma = soma + valor;
        }
        if (!TxtCodVenda.getText().equals("")) {
            mv.setIdvenda(Integer.parseInt(TxtCodVenda.getText()));
        }
        mv.setIdcliente(Integer.parseInt(TxtCodClie.getText()));
        mv.setValor(soma);
        mv.setDesconto(Double.parseDouble(TxtDesconto.getText()));
        mv.setValortotal(Double.parseDouble(TxtValotTotal.getText()));

        if (alterarSalvar.equals("salvar")) {
            //Salvar a venda

            codigoVenda = cv.salvarvendaController(mv);
            if (codigoVenda > 0) {
                JOptionPane.showMessageDialog(this, "Venda Salva com Sucesso!", "Informação", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "venda Não Salva!", "Erro", JOptionPane.ERROR_MESSAGE);
            }

            for (int i = 0; i < cont; i++) {
                int codigoP = (int) TbProduto.getValueAt(i, 0);
                miv = new ModelItensVenda();
                mp = new ModelProduto();
                miv.setCodproduto(codigoP);
                miv.setCodvenda(codigoVenda);
                miv.setItensvalor((double) TbProduto.getValueAt(i, 3));
                miv.setIntensqtd(Integer.parseInt(TbProduto.getValueAt(i, 2).toString()));

                //Produto
                mp.setIdProduto((int) TbProduto.getValueAt(i, 0));
                mp.setProEstoque(cp.listarProduto(codigoP).getProEstoque() - Integer.parseInt(TbProduto.getValueAt(i, 2).toString()));
                listaIV.add(miv);
                listaProduto.add(mp);
            }
            if (civ.salvarItensVendaController(listaIV)) {
                cp.alterarEstoqueProdutoController(listaProduto);
                // JOptionPane.showMessageDialog(this, "Itens da Venda Salvo com Sucesso!", "Informação", JOptionPane.INFORMATION_MESSAGE);
                this.carregarVenda();
                this.limparCampos();
                TPVenda.setSelectedIndex(1);
            } else {
                JOptionPane.showMessageDialog(this, "Itens da Venda Não Salvo!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            //Alterar

            //Retornar os itens ao estoque:
            int linha = TbVenda.getSelectedRow();
            codigoVenda = (int) TbVenda.getValueAt(linha, 0);
            listaProduto = new ArrayList<>();
            listaIVP = cIVP.getListaItensvendaProdutoDao(codigoVenda);
            for (int i = 0; i < listaIVP.size(); i++) {
                mp = new ModelProduto();
                mp.setIdProduto(listaIVP.get(i).getMprodutos().getIdProduto());
                mp.setProEstoque(listaIVP.get(i).getMprodutos().getProEstoque() + listaIVP.get(i).getmItensVenda().getIntensqtd());
                listaProduto.add(mp);
            }
            if (cp.alterarEstoqueProdutoController(listaProduto)) {

                if (civ.eliminarItensVendaController(codigoVenda)) {

                    //  JOptionPane.showMessageDialog(this, "Itens da Venda Eliminada com Sucesso!", "Informação", JOptionPane.INFORMATION_MESSAGE);
                    this.carregarVenda();

                } else {
                    JOptionPane.showMessageDialog(this, "Itens da Venda Não Eliminada!", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Venda Não Eliminada!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
            //Fim Retornar os itens ao estoque:

            if (cv.atualizarvendaController(mv)) {
                JOptionPane.showMessageDialog(this, "Venda Alterada com Sucesso!", "Informação", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Venda Não Alterada", "Erro", JOptionPane.ERROR_MESSAGE);
            }
            for (int i = 0; i < cont; i++) {
                int codigoP = (int) TbProduto.getValueAt(i, 0);
                miv = new ModelItensVenda();
                mp = new ModelProduto();
                miv.setCodproduto(codigoP);
                miv.setCodvenda(codigoVenda);
                miv.setItensvalor((double) TbProduto.getValueAt(i, 3));
                miv.setIntensqtd(Integer.parseInt(TbProduto.getValueAt(i, 2).toString()));

                //Produto
                mp.setIdProduto((int) TbProduto.getValueAt(i, 0));
                mp.setProEstoque(cp.listarProduto(codigoP).getProEstoque() - Integer.parseInt(TbProduto.getValueAt(i, 2).toString()));
                listaIV.add(miv);
                listaProduto.add(mp);
            }
            if (civ.salvarItensVendaController(listaIV)) {
                // JOptionPane.showMessageDialog(this, "Itens da Venda Salvo com Sucesso!", "Informação", JOptionPane.INFORMATION_MESSAGE);
                this.carregarVenda();
                this.limparCampos();
            } else {
                JOptionPane.showMessageDialog(this, "Itens da Venda Não Salvo!", "Erro", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_BtnSalvarActionPerformed

    private void BtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAlterarActionPerformed
        alterarSalvar = "alterar";
        BtnCancelar.setEnabled(true);
        BtnSalvar.setEnabled(true);
        BtnNovo.setEnabled(false);
        int linha = TbVenda.getSelectedRow();
        int codigoVenda = (int) TbVenda.getValueAt(linha, 0);
        listaIVP = cIVP.getListaItensvendaProdutoDao(codigoVenda);
        DefaultTableModel modelo = (DefaultTableModel) TbProduto.getModel();
        modelo.setNumRows(0);
        for (int i = 0; i < listaIVP.size(); i++) {
            TxtCodVenda.setText("" + listaIVP.get(i).getmItensVenda().getCodvenda());
            modelo.addRow(new Object[]{listaIVP.get(i).getMprodutos().getIdProduto(), listaIVP.get(i).getMprodutos().getProNome(), listaIVP.get(i).getmItensVenda().getIntensqtd(), listaIVP.get(i).getmItensVenda().getItensvalor(), listaIVP.get(i).getmItensVenda().getItensvalor() * listaIVP.get(i).getmItensVenda().getIntensqtd()});
        }
        this.somaValorTotal();
        TPVenda.setSelectedIndex(0);
    }//GEN-LAST:event_BtnAlterarActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        int venda = TbVenda.getSelectedRow();
        int confirma = JOptionPane.showConfirmDialog(this, "Tem certesa que deseja eliminar a venda: " + TbVenda.getValueAt(venda, 0) + "?", "Atenção", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (confirma == JOptionPane.YES_OPTION) {
            int linha = TbVenda.getSelectedRow();
            int codigoVenda = (int) TbVenda.getValueAt(linha, 0);
            listaProduto = new ArrayList<>();
            listaIVP = cIVP.getListaItensvendaProdutoDao(codigoVenda);
            for (int i = 0; i < listaIVP.size(); i++) {
                mp = new ModelProduto();
                mp.setIdProduto(listaIVP.get(i).getMprodutos().getIdProduto());
                mp.setProEstoque(listaIVP.get(i).getMprodutos().getProEstoque() + listaIVP.get(i).getmItensVenda().getIntensqtd());
                listaProduto.add(mp);
            }
            if (cp.alterarEstoqueProdutoController(listaProduto)) {
                civ.eliminarItensVendaController(codigoVenda);
                if (cv.excluirvendaController(codigoVenda)) {
                    JOptionPane.showMessageDialog(this, "Venda Eliminada com Sucesso!", "Informação", JOptionPane.INFORMATION_MESSAGE);
                    this.carregarVenda();

                } else {
                    JOptionPane.showMessageDialog(this, "Venda Não Eliminada!", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Venda Não Eliminada!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void TxtCodClieMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtCodClieMouseExited
        if (!TxtCodClie.getText().isEmpty()) {
            mdc = cc.listarCliente(Integer.parseInt(TxtCodClie.getText()));
            CbNomeCli.setSelectedItem(mdc.getCliNome());
        }
    }//GEN-LAST:event_TxtCodClieMouseExited

    private void TxtCodProdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtCodProdMouseExited
        if (!TxtCodProd.getText().isEmpty()) {
            mp = cp.listarProduto(Integer.parseInt(TxtCodProd.getText()));
            CbProduto.setSelectedItem(mp.getProNome());
        }
    }//GEN-LAST:event_TxtCodProdMouseExited

    private void BtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddActionPerformed
        if (TxtQtd.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campos Vazios! Prerncha os campos vazios!", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else {
            TxtDesconto.setEnabled(true);
            TxtDesconto.setText("" + 0);
            mp = cp.listarProduto(Integer.parseInt(TxtCodProd.getText()));
            DefaultTableModel modelo = (DefaultTableModel) TbProduto.getModel();
            int cont = 0;
            double qtd = 0;
            qtd = Double.parseDouble(TxtQtd.getText());
            for (int i = 0; i < cont; i++) {
                modelo.setNumRows(0);
            }
            modelo.addRow(new Object[]{
                mp.getIdProduto(),
                mp.getProNome(),
                TxtQtd.getText(),
                mp.getProValor(),
                qtd * mp.getProValor()
            });
            this.somaValorTotal();
        }
        BtnSalvar.setEnabled(true);
    }//GEN-LAST:event_BtnAddActionPerformed

    private void TxtDescontoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtDescontoMouseExited

    }//GEN-LAST:event_TxtDescontoMouseExited

    private void TxtDescontoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtDescontoFocusLost

        this.aplicarDesconto();
    }//GEN-LAST:event_TxtDescontoFocusLost

    private void TxtDescontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDescontoActionPerformed
        if (TxtDesconto.getText().equals("")) {
            int confirma = JOptionPane.showConfirmDialog(this, "Deseja Aplicar desconto a essa venda ?", "Informação", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (confirma == JOptionPane.YES_OPTION) {
                JOptionPane.showMessageDialog(this, "Informa a quantidade a ser descontado", "Atenção", JOptionPane.WARNING_MESSAGE);
                TxtDesconto.requestFocus();
            } else {
                this.somaValorTotal();
            }
        } else {
            somaValorTotal();
        }
    }//GEN-LAST:event_TxtDescontoActionPerformed

    private void MPRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MPRemoverActionPerformed
        int linha = TbProduto.getSelectedRow();
        DefaultTableModel dtm = (DefaultTableModel) TbProduto.getModel();
        dtm.removeRow(linha);
        this.somaValorTotal();
    }//GEN-LAST:event_MPRemoverActionPerformed

    private void CbProdutoPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_CbProdutoPopupMenuWillBecomeInvisible
        if (CbProduto.isPopupVisible()) {
            carregarComboProduto();
        }
    }//GEN-LAST:event_CbProdutoPopupMenuWillBecomeInvisible

    private void CbNomeCliPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_CbNomeCliPopupMenuWillBecomeInvisible
        if (CbNomeCli.isPopupVisible()) {
            carregarComboCliente();
        }
    }//GEN-LAST:event_CbNomeCliPopupMenuWillBecomeInvisible

    private void TbVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbVendaMouseClicked
        if (TbVenda.getSelectedRow() > 0) {
            BtnAlterar.setEnabled(true);
            BtnEliminar.setEnabled(true);
        } else {
            BtnAlterar.setEnabled(false);
            BtnEliminar.setEnabled(false);
        }
    }//GEN-LAST:event_TbVendaMouseClicked

    private void TxtQtdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtQtdMouseExited
        if (!TxtQtd.getText().equals("")) {
            BtnAdd.setEnabled(true);
        }
    }//GEN-LAST:event_TxtQtdMouseExited

    private void BtnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnImprimirActionPerformed
        int linha = TbVenda.getSelectedRow();       
        final int Codvenda = (int) TbVenda.getValueAt(linha, 0);
        final ViewUtili vu= new ViewUtili();
        vu.setVisible(true);
        Thread tr=new Thread(){
            public void run(){
                try {
                    
                    cv.imprimirRelvendasControoller(Codvenda);
                    vu.dispose();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Erro ao Gerar o Relatório! \n" + e, "Erro", JOptionPane.ERROR_MESSAGE);
                }
                
            }
        };
        tr.start();
        
    }//GEN-LAST:event_BtnImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdd;
    private javax.swing.JButton BtnAlterar;
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnImprimir;
    private javax.swing.JButton BtnNovo;
    private javax.swing.JButton BtnPesquisar;
    private javax.swing.JButton BtnSalvar;
    private componentes.UJComboBox CbNomeCli;
    private componentes.UJComboBox CbProduto;
    private javax.swing.JPopupMenu MPProduto;
    private javax.swing.JMenuItem MPRemover;
    private javax.swing.JTabbedPane TPVenda;
    private javax.swing.JTable TbProduto;
    private javax.swing.JTable TbVenda;
    private javax.swing.JTextField TxtCodClie;
    private javax.swing.JTextField TxtCodProd;
    private javax.swing.JTextField TxtCodVenda;
    private javax.swing.JTextField TxtDesconto;
    private javax.swing.JTextField TxtPesquisar;
    private javax.swing.JFormattedTextField TxtQtd;
    private javax.swing.JFormattedTextField TxtValotTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    private void listarCliente() {
        listaCliente = cc.listaClienteControllerCliente("");
        CbNomeCli.removeAllItems();
        for (int i = 0; i < listaCliente.size(); i++) {
            CbNomeCli.addItem(listaCliente.get(i).getCliNome());

        }
    }

    private void listarProduto() {
        listaProduto = cp.listaProdutoControllerProduto("");
        CbProduto.removeAllItems();
        for (int i = 0; i < listaProduto.size(); i++) {
            CbProduto.addItem(listaProduto.get(i).getProNome());

        }
    }

    private void carregarVenda() {
        DefaultTableModel dfm = (DefaultTableModel) TbVenda.getModel();
        dfm.setNumRows(0);
        listaCli = cvc.getListavendaClieController();
        int cont = listaCli.size();
        for (int i = 0; i < cont; i++) {
            dfm.addRow(new Object[]{
                listaCli.get(i).getModelVenda().getIdvenda(),
                listaCli.get(i).getModelCli().getCliNome(),
                listaCli.get(i).getModelVenda().getDatavenda()
            });

        }
    }

    private void somaValorTotal() {
        double soma = 0, valor;
        int cont = TbProduto.getRowCount();
        for (int i = 0; i < cont; i++) {
            valor = (double) TbProduto.getValueAt(i, 4);
            soma = soma + valor;
        }
        TxtValotTotal.setText(String.valueOf(soma));
        aplicarDesconto();
    }

    private void aplicarDesconto() {
        double valor = Double.parseDouble(TxtValotTotal.getText());
        double desc = Double.parseDouble(TxtDesconto.getText());
        double valorComDesconto = valor - (valor * (desc / 100));
        TxtValotTotal.setText("" + valorComDesconto);

    }

    public void carregarComboProduto() {
        mp = cp.listarProdutoNome(CbProduto.getSelectedItem().toString());
        TxtCodProd.setText(String.valueOf(mp.getIdProduto()));
    }

    public void carregarComboCliente() {
        mdc = cc.listarClienteNome(CbNomeCli.getSelectedItem().toString());
        TxtCodClie.setText(String.valueOf(mdc.getIdCliente()));
    }

    private void limparCampos() {
        TxtQtd.setText("");
        TxtCodVenda.setText("");
        TxtValotTotal.setText("");
        TxtDesconto.setText("" + 0);
        DefaultTableModel dtm = (DefaultTableModel) TbProduto.getModel();
        dtm.setNumRows(0);

    }

    private void btnNovo() {
        TxtQtd.setEnabled(true);
        TxtCodClie.setEnabled(true);
        TxtCodProd.setEnabled(true);
        CbNomeCli.setEnabled(true);
        CbProduto.setEnabled(true);
    }
}
