/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerUsuario;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ModelUsuario;

/**
 *
 * @author AurelioTEC
 */
public class ViewUsuario extends javax.swing.JFrame {

    ArrayList<ModelUsuario> listaUsuario = new ArrayList<>();
    ControllerUsuario cu = new ControllerUsuario();
    ModelUsuario mu = new ModelUsuario();
    String alterarSalvar;

    /**
     * Creates new form ViewUsuario
     */
    public ViewUsuario() {
        initComponents();
        setLocationRelativeTo(null);
        this.carregarUsuario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TxtCodigo = new javax.swing.JTextField();
        TxtLogin = new javax.swing.JTextField();
        TxtNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BtnNovo = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        BtnAlterar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        BtnSalvar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TbUsuario = new javax.swing.JTable();
        TxtSenhaRepetida = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        TxtSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setEnabled(false);

        TxtCodigo.setEnabled(false);

        TxtLogin.setEnabled(false);

        TxtNome.setEnabled(false);

        jLabel1.setText("Codigo");

        jLabel2.setText("Nome");

        jLabel3.setText("Login");

        jLabel4.setText("Senha");

        BtnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/file_18px.png"))); // NOI18N
        BtnNovo.setText("Novo");
        BtnNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNovoActionPerformed(evt);
            }
        });

        BtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/cancel_18px.png"))); // NOI18N
        BtnCancelar.setText("Cancelar");
        BtnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnCancelar.setEnabled(false);
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        BtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/edit_18px.png"))); // NOI18N
        BtnAlterar.setText("Alterar");
        BtnAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAlterar.setEnabled(false);
        BtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAlterarActionPerformed(evt);
            }
        });

        BtnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/delete_18px.png"))); // NOI18N
        BtnEliminar.setText("Eliminar");
        BtnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnEliminar.setEnabled(false);
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        BtnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/save_18px.png"))); // NOI18N
        BtnSalvar.setText("Salvar");
        BtnSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnSalvar.setEnabled(false);
        BtnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnSalvarMouseEntered(evt);
            }
        });
        BtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalvarActionPerformed(evt);
            }
        });

        TbUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Login"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbUsuario.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TbUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbUsuarioMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TbUsuario);
        if (TbUsuario.getColumnModel().getColumnCount() > 0) {
            TbUsuario.getColumnModel().getColumn(1).setMinWidth(250);
            TbUsuario.getColumnModel().getColumn(1).setPreferredWidth(250);
            TbUsuario.getColumnModel().getColumn(2).setMinWidth(150);
            TbUsuario.getColumnModel().getColumn(2).setPreferredWidth(150);
        }

        TxtSenhaRepetida.setEnabled(false);
        TxtSenhaRepetida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TxtSenhaRepetidaMouseExited(evt);
            }
        });

        jLabel5.setText("Repetir Senha");

        TxtSenha.setEnabled(false);
        TxtSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtSenhaFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtNome))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(BtnNovo)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(BtnAlterar)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(BtnCancelar)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(BtnEliminar)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(BtnSalvar))
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(324, 324, 324))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(TxtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtSenhaRepetida)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtSenhaRepetida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnNovo)
                    .addComponent(BtnEliminar)
                    .addComponent(BtnSalvar)
                    .addComponent(BtnAlterar)
                    .addComponent(BtnCancelar))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNovoActionPerformed
        alterarSalvar = "salvar";
        this.limparCampos();
        this.btnNovo();
    }//GEN-LAST:event_BtnNovoActionPerformed

    private void BtnSalvarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSalvarMouseEntered

    }//GEN-LAST:event_BtnSalvarMouseEntered

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        this.limparCampos();
        this.btnCancelar();
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void BtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAlterarActionPerformed
        alterarSalvar = "alterar";
        int linha = TbUsuario.getSelectedRow();
        int codigo = (int) TbUsuario.getValueAt(linha, 0);
        mu = cu.listarUsuarioCodigo(codigo);
        TxtCodigo.setText(String.valueOf(mu.getIdusario()));
        TxtNome.setText(mu.getNomeusu());
        TxtLogin.setText(mu.getLogin());
        TxtSenha.setText(mu.getSenha());
        btnNovo();
        TbUsuario.setSelectionBackground(Color.white);
        TbUsuario.setSelectionForeground(Color.BLACK);
    }//GEN-LAST:event_BtnAlterarActionPerformed

    private void BtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvarActionPerformed
        if (TxtSenhaRepetida.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo Senha Vazio!", "Informação", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if (alterarSalvar.equals("salvar")) {
                this.salvarUsuario();
            } else {
                this.alterarUsuario();
            }
        }
    }//GEN-LAST:event_BtnSalvarActionPerformed

    private void TbUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbUsuarioMouseClicked

        if (TbUsuario.getSelectedRow() != -1) {
            TbUsuario.setSelectionBackground(Color.blue);
            TbUsuario.setSelectionForeground(Color.WHITE);
            BtnNovo.setEnabled(false);
            BtnAlterar.setEnabled(true);
            BtnEliminar.setEnabled(true);
        }
    }//GEN-LAST:event_TbUsuarioMouseClicked

    private void TxtSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtSenhaFocusLost
        if (TxtSenha.getText().length() < 6) {
            JOptionPane.showMessageDialog(this, "A senha deve ter no minimo 6 caracteres!", "Informação", JOptionPane.INFORMATION_MESSAGE);
            TxtSenha.requestFocus();
        } else {
            TxtSenhaRepetida.requestFocus();
        }
    }//GEN-LAST:event_TxtSenhaFocusLost

    private void TxtSenhaRepetidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtSenhaRepetidaMouseExited
        if (TxtSenhaRepetida.getText().equals("")) {
            TxtSenhaRepetida.requestFocus();
        } else if (TxtSenhaRepetida.getText().length() < 6) {
            JOptionPane.showMessageDialog(this, "A senha deve ter no minimo 6 caracteres!", "Informação", JOptionPane.INFORMATION_MESSAGE);
        } else if (!TxtSenhaRepetida.getText().equals(TxtSenha.getText())) {
            JOptionPane.showMessageDialog(this, "As Senhas digitadas são diferentes !", "Informação", JOptionPane.INFORMATION_MESSAGE);
            TxtSenhaRepetida.requestFocus();
        } else {
            BtnSalvar.setEnabled(true);
        }
    }//GEN-LAST:event_TxtSenhaRepetidaMouseExited

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        int Usu = TbUsuario.getSelectedRow();
        int confirma = JOptionPane.showConfirmDialog(this, "Tem certesa que deseja eliminar o Usuario: " + TbUsuario.getValueAt(Usu, 1) + "?", "Atenção", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (confirma == JOptionPane.YES_OPTION) {
            int linha = TbUsuario.getSelectedRow();
            int codigo = (int) TbUsuario.getValueAt(linha, 0);
            if (cu.eliminarControllerUsuario(codigo)) {
                JOptionPane.showMessageDialog(this, "Usuario eliminado com sucesso!", "Informação", JOptionPane.INFORMATION_MESSAGE);
                this.carregarUsuario();
                this.btnCancelar();
            } else {
                JOptionPane.showMessageDialog(this, "Usuario não eliminado!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_BtnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAlterar;
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnNovo;
    private javax.swing.JButton BtnSalvar;
    private javax.swing.JTable TbUsuario;
    private javax.swing.JTextField TxtCodigo;
    private javax.swing.JTextField TxtLogin;
    private javax.swing.JTextField TxtNome;
    private javax.swing.JPasswordField TxtSenha;
    private javax.swing.JPasswordField TxtSenhaRepetida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
 private void salvarUsuario() {
        mu.setNomeusu(TxtNome.getText());
        mu.setLogin(TxtLogin.getText());
        mu.setSenha(String.valueOf(TxtSenhaRepetida.getPassword()));

        if (cu.cadastrarControllerUsuario(mu) > 0) {
            JOptionPane.showMessageDialog(this, "Usuario Cadastrdo com Sucesso!", "Informação", JOptionPane.INFORMATION_MESSAGE);
            this.carregarUsuario();
            this.limparCampos();
            this.btnCancelar();
        } else {
            JOptionPane.showMessageDialog(this, "Usuario Não Cadastrado!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void alterarUsuario() {
        mu.setIdusario(Integer.parseInt(TxtCodigo.getText()));
        mu.setNomeusu(TxtNome.getText());
        mu.setLogin(TxtLogin.getText());
        mu.setSenha(String.valueOf(TxtSenhaRepetida.getPassword()));
        if (cu.alterarControllerUsuario(mu)) {
            JOptionPane.showMessageDialog(this, "Usuario Alterado com Sucesso!", "Informação", JOptionPane.INFORMATION_MESSAGE);
            this.carregarUsuario();
            this.limparCampos();
            this.btnCancelar();
        } else {
            JOptionPane.showMessageDialog(this, "Usuario Não Alterado!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void carregarUsuario() {
        listaUsuario = cu.listaUsuarioControllerUsuario();
        DefaultTableModel dtm = (DefaultTableModel) TbUsuario.getModel();
        dtm.setNumRows(0);
        int cont = listaUsuario.size();
        for (int i = 0; i < cont; i++) {
            dtm.addRow(new Object[]{
                listaUsuario.get(i).getIdusario(),
                listaUsuario.get(i).getNomeusu(),
                listaUsuario.get(i).getLogin()
            });
        }
    }

    private void limparCampos() {
        TxtCodigo.setText("");
        TxtNome.setText("");
        TxtLogin.setText("");
        TxtSenha.setText("");
        TxtSenhaRepetida.setText("");
    }

    private void btnNovo() {
        TxtCodigo.setEnabled(true);
        TxtCodigo.setEditable(false);
        TxtNome.setEnabled(true);
        TxtNome.requestFocus();
        TxtLogin.setEnabled(true);
        TxtSenha.setEnabled(true);
        TxtSenhaRepetida.setEnabled(true);
        BtnNovo.setEnabled(false);
        BtnCancelar.setEnabled(true);
        BtnAlterar.setEnabled(false);
        BtnEliminar.setEnabled(false);
        BtnSalvar.setEnabled(false);
    }

    private void btnCancelar() {
        TxtCodigo.setEnabled(false);
        TxtNome.setEnabled(false);
        TxtLogin.setEnabled(false);
        TxtSenha.setEnabled(false);
        TxtSenhaRepetida.setEnabled(false);
        BtnNovo.setEnabled(true);
        BtnCancelar.setEnabled(false);
        BtnAlterar.setEnabled(false);
        BtnEliminar.setEnabled(false);
        BtnSalvar.setEnabled(false);
    }

}
