/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerProduto;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ModelProduto;
import utilitario.Utilitario;

/**
 *
 * @author AurelioTEC
 */
public class ViewProduto extends javax.swing.JFrame {

    ArrayList<ModelProduto> lista = new ArrayList<>();
    ControllerProduto cp = new ControllerProduto();
    ModelProduto mp = new ModelProduto();
    String salvarAlterar;
    Utilitario ut = new Utilitario();

    /**
     * Creates new form ViewCliente
     */
    public ViewProduto() {
        initComponents();
        carregarProduto();
        setLocationRelativeTo(null);
        limparBloquear();
        bloquerBotoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TxtCodigoProd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtNomeProd = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtPesquisar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbProduto = new javax.swing.JTable();
        BtnNovo = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        BtnPesquisar = new javax.swing.JButton();
        BtnSalvar = new javax.swing.JButton();
        BtnAlterar = new javax.swing.JButton();
        TxtEstoque = new javax.swing.JFormattedTextField();
        TxtValor = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Produtos");
        setResizable(false);

        jLabel1.setText("Codigo");

        jLabel2.setText("Nome");

        TxtNomeProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TxtNomeProdMouseReleased(evt);
            }
        });
        TxtNomeProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtNomeProdKeyReleased(evt);
            }
        });

        jLabel3.setText("Estoque");

        jLabel4.setText("Valor");

        jLabel5.setText("Pesquisar");

        TxtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtPesquisarKeyReleased(evt);
            }
        });

        TbProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Quantidade", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbProduto.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TbProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbProdutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TbProduto);
        if (TbProduto.getColumnModel().getColumnCount() > 0) {
            TbProduto.getColumnModel().getColumn(1).setMinWidth(300);
            TbProduto.getColumnModel().getColumn(1).setPreferredWidth(300);
        }

        BtnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/file_18px.png"))); // NOI18N
        BtnNovo.setText("Novo");
        BtnNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNovoActionPerformed(evt);
            }
        });

        BtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/cancel_18px.png"))); // NOI18N
        BtnCancelar.setText("Cancelar");
        BtnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        BtnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/delete_18px.png"))); // NOI18N
        BtnEliminar.setText("Eliminar");
        BtnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        BtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/search_18px.png"))); // NOI18N
        BtnPesquisar.setText("Pesquisar");
        BtnPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPesquisarActionPerformed(evt);
            }
        });

        BtnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/save_18px.png"))); // NOI18N
        BtnSalvar.setText("Salvar");
        BtnSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalvarActionPerformed(evt);
            }
        });

        BtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/edit_18px.png"))); // NOI18N
        BtnAlterar.setText("Alterar");
        BtnAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAlterarActionPerformed(evt);
            }
        });

        TxtEstoque.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        TxtValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#######.##"))));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TxtCodigoProd)
                            .addComponent(TxtEstoque)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(70, 70, 70)))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtNomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(TxtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BtnNovo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnSalvar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtCodigoProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtNomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(BtnPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCancelar)
                    .addComponent(BtnNovo)
                    .addComponent(BtnSalvar)
                    .addComponent(BtnEliminar)
                    .addComponent(BtnAlterar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNovoActionPerformed
        salvarAlterar = "Salvar";
        this.desbloquear();
        TxtNomeProd.requestFocus();
    }//GEN-LAST:event_BtnNovoActionPerformed

    private void BtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvarActionPerformed
        if (salvarAlterar.equals("Salvar")) {
            this.salvarProduto();
        } else if (salvarAlterar.equals("Alterar")) {
            this.alterarProduto();
        }
    }//GEN-LAST:event_BtnSalvarActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        int cli = TbProduto.getSelectedRow();
        int confirma = JOptionPane.showConfirmDialog(this, "Tem certesa que deseja eliminar : " + TbProduto.getValueAt(cli, 1) + "?", "Atenção", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (confirma == JOptionPane.YES_OPTION) {
            int linha = TbProduto.getSelectedRow();
            int codigo = (int) TbProduto.getValueAt(linha, 0);
            if (cp.eliminarControllerProduto(codigo)) {
                JOptionPane.showMessageDialog(this, "Produto Eliminado com Sucesso!", "Informação", JOptionPane.INFORMATION_MESSAGE);
                this.carregarProduto();
                this.bloquerBotoes();
            } else {
                JOptionPane.showMessageDialog(this, "Produto Não Eliminado!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        this.limparBloquear();
        this.bloquerBotoes();
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void TxtNomeProdMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtNomeProdMouseReleased

    }//GEN-LAST:event_TxtNomeProdMouseReleased

    private void TxtNomeProdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNomeProdKeyReleased
        if ((TxtNomeProd.getText().length() > 3 || (!TxtEstoque.getText().equals("") || (!TxtValor.getText().equals(""))))) {
            BtnCancelar.setEnabled(true);
            BtnSalvar.setEnabled(true);
        }
    }//GEN-LAST:event_TxtNomeProdKeyReleased

    private void BtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPesquisarActionPerformed
        this.pesquisar();
        TxtPesquisar.setText("");
    }//GEN-LAST:event_BtnPesquisarActionPerformed

    private void TxtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPesquisarKeyReleased
        if (TxtPesquisar.getText().length() > 3) {
            BtnPesquisar.setEnabled(true);
        }
    }//GEN-LAST:event_TxtPesquisarKeyReleased

    private void BtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAlterarActionPerformed
        salvarAlterar = "Alterar";
        int linha = TbProduto.getSelectedRow();
        try {
            int codigo = (int) TbProduto.getValueAt(linha, 0);
            mp = cp.listarProduto(codigo);
            TxtCodigoProd.setText(String.valueOf(mp.getIdProduto()));
            TxtNomeProd.setText(mp.getProNome());
            TxtEstoque.setText(String.valueOf(mp.getProEstoque()));
            TxtValor.setText(String.valueOf(mp.getProValor()));
            this.desbloquear();
            BtnAlterar.setEnabled(false);
            BtnCancelar.setEnabled(true);
            BtnEliminar.setEnabled(false);
            BtnSalvar.setEnabled(true);
            BtnNovo.setEnabled(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Seleciona o Produto a Ser Alterado! ", "Informação", JOptionPane.INFORMATION_MESSAGE);
        }


    }//GEN-LAST:event_BtnAlterarActionPerformed

    private void TbProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbProdutoMouseClicked
        int linha = TbProduto.getSelectedRow();
        if (linha != 0) {
            BtnAlterar.setEnabled(true);
            BtnEliminar.setEnabled(true);
        }
    }//GEN-LAST:event_TbProdutoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewProduto().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAlterar;
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnNovo;
    private javax.swing.JButton BtnPesquisar;
    private javax.swing.JButton BtnSalvar;
    private javax.swing.JTable TbProduto;
    private javax.swing.JTextField TxtCodigoProd;
    private javax.swing.JFormattedTextField TxtEstoque;
    private javax.swing.JTextField TxtNomeProd;
    private javax.swing.JTextField TxtPesquisar;
    private javax.swing.JFormattedTextField TxtValor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void limparBloquear() {
        TxtEstoque.setText("");
        TxtNomeProd.setText("");
        TxtValor.setText("");
        TxtCodigoProd.setText("");
        TxtPesquisar.setText("");
        TxtEstoque.setEnabled(false);
        TxtNomeProd.setEnabled(false);
        TxtValor.setEnabled(false);
        TxtCodigoProd.setEnabled(false);
    }

    private void bloquerBotoes() {
        BtnNovo.setEnabled(true);
        BtnAlterar.setEnabled(false);
        BtnCancelar.setEnabled(false);
        BtnEliminar.setEnabled(false);
        BtnSalvar.setEnabled(false);
        BtnPesquisar.setEnabled(false);
    }

    private void desbloquear() {
        TxtEstoque.setEnabled(true);
        TxtNomeProd.setEnabled(true);
        TxtValor.setEnabled(true);
    }

    private void carregarProduto() {
        lista = cp.listaProdutoControllerProduto("");
        DefaultTableModel modelo = (DefaultTableModel) TbProduto.getModel();
        modelo.setNumRows(0);
        int cont = lista.size();
        for (int i = 0; i < cont; i++) {
            modelo.addRow(new Object[]{
                lista.get(i).getIdProduto(),
                lista.get(i).getProNome(),
                lista.get(i).getProValor(),
                lista.get(i).getProEstoque()
            });
        }
    }

    public void salvarProduto() {
        mp.setProNome(TxtNomeProd.getText());
        mp.setProEstoque(Integer.parseInt(TxtEstoque.getText()));
        mp.setProValor(ut.virgulaParaPonto(TxtValor.getText()));
        if (cp.cadastrarControllerProdutos(mp) > 0) {
            JOptionPane.showMessageDialog(this, "Produto Cadastrdo com Sucesso!", "Informação", JOptionPane.INFORMATION_MESSAGE);
            this.carregarProduto();
            this.limparBloquear();
            this.bloquerBotoes();
        } else {
            JOptionPane.showMessageDialog(this, "Produto Não Cadastrdo!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void pesquisar() {
        DefaultTableModel dfm = (DefaultTableModel) TbProduto.getModel();
        dfm.setNumRows(0);
        for (ModelProduto mps : cp.listaProdutoControllerProduto(TxtPesquisar.getText())) {
            Object[] dados = {mps.getIdProduto(), mps.getProNome(), mps.getProEstoque(), mps.getProValor()};
            dfm.addRow(dados);
        }
    }

    public void alterarProduto() {
        mp.setProNome(TxtNomeProd.getText());
        mp.setProEstoque(Integer.parseInt(TxtEstoque.getText()));
        mp.setProValor(ut.virgulaParaPonto(TxtValor.getText()));
        if (cp.alterarControllerProduto(mp)) {
            JOptionPane.showMessageDialog(this, "Produto Alterado com Sucesso!", "Informação", JOptionPane.INFORMATION_MESSAGE);
            this.carregarProduto();
            this.limparBloquear();
            this.bloquerBotoes();
        } else {
            JOptionPane.showMessageDialog(this, "Produto Não Alterado!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

}
