/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.sun.glass.events.KeyEvent;
import controller.ControllerCliente;
import controller.ControllerFormaPagamento;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.ModelCliente;
import model.ModelFormaPagamento;

/**
 *
 * @author AurelioTEC
 */
public class ViewPagamentoPDV extends javax.swing.JDialog {

    ArrayList<ModelFormaPagamento> listaMFP = new ArrayList<>();
    ArrayList<ModelCliente> listaCliente = new ArrayList<>();
    ControllerCliente cc = new ControllerCliente();
    ControllerFormaPagamento CFP = new ControllerFormaPagamento();
    ModelCliente mdc = new ModelCliente();
    private double subtotal;
    private double desconto;
    private double valorRecebido;
    private double troco;
    private String formaPag;
    private boolean pago;
    int CodCLi;
    int valor;

    /**
     * Creates new form ViewPagamentoPDV
     */
    public ViewPagamentoPDV(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.listarFormaPagamento();
        this.pago = false;
        this.listarCliente();
        this.carregarComboCliente();
        TxtValorRecebido.setText(""+0);
        Txtdesconto.setText(""+0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        LbTroco = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        LbTotal = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxtValorRecebido = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        CBPagamento = new javax.swing.JComboBox<>();
        TxtSubtotal = new javax.swing.JFormattedTextField();
        Txtdesconto = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CbNomeCli = new componentes.UJComboBox();
        BtnOK = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        BtnCinco = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        BtnDez = new javax.swing.JButton();
        BtnCinquenta = new javax.swing.JButton();
        BtnQuinhento = new javax.swing.JButton();
        BtnCem = new javax.swing.JButton();
        BtnMil = new javax.swing.JButton();
        BtnCincomil = new javax.swing.JButton();
        BtnDoismil = new javax.swing.JButton();
        BtnLimparValor = new javax.swing.JButton();
        BtnLimparValor1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Troco", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("sansserif", 1, 24))); // NOI18N

        LbTroco.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        LbTroco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbTroco.setText("Troco");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LbTroco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(LbTroco)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Valor a Pagar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("sansserif", 1, 24))); // NOI18N

        LbTotal.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        LbTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbTotal.setText("Total a Pagar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LbTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(LbTotal)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setText("Pagamento");

        TxtValorRecebido.setEditable(false);
        TxtValorRecebido.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        TxtValorRecebido.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        TxtValorRecebido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtValorRecebidoFocusLost(evt);
            }
        });
        TxtValorRecebido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtValorRecebidoActionPerformed(evt);
            }
        });
        TxtValorRecebido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtValorRecebidoKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel3.setText("Subtotal");

        CBPagamento.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N

        TxtSubtotal.setEditable(false);
        TxtSubtotal.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N

        Txtdesconto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        Txtdesconto.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        Txtdesconto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtdescontoFocusLost(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setText("Desconto");

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel4.setText("Valor Recebido");

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Selecionar Cliente");

        CbNomeCli.setAutocompletar(true);
        CbNomeCli.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        CbNomeCli.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                CbNomeCliPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        CbNomeCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbNomeCliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CBPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txtdesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CbNomeCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TxtValorRecebido, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txtdesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtValorRecebido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbNomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        BtnOK.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        BtnOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/ok_24px.png"))); // NOI18N
        BtnOK.setText("OK");
        BtnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOKActionPerformed(evt);
            }
        });

        BtnCinco.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        BtnCinco.setText("5 ");
        BtnCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCincoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel5.setText("Escolha as Notas");

        BtnDez.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        BtnDez.setText("10");
        BtnDez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDezActionPerformed(evt);
            }
        });

        BtnCinquenta.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        BtnCinquenta.setText("50");
        BtnCinquenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCinquentaActionPerformed(evt);
            }
        });

        BtnQuinhento.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        BtnQuinhento.setText("500");
        BtnQuinhento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnQuinhentoActionPerformed(evt);
            }
        });

        BtnCem.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        BtnCem.setText("100");
        BtnCem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCemActionPerformed(evt);
            }
        });

        BtnMil.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        BtnMil.setText("1000");
        BtnMil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMilActionPerformed(evt);
            }
        });

        BtnCincomil.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        BtnCincomil.setText("5000");
        BtnCincomil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCincomilActionPerformed(evt);
            }
        });

        BtnDoismil.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        BtnDoismil.setText("2000");
        BtnDoismil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDoismilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(38, 38, 38))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnCinco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnDez, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnCinquenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnQuinhento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnCem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnMil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnCincomil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnDoismil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnDez, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnCinquenta, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnCem, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnQuinhento, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnMil, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(BtnDoismil, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnCincomil, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BtnLimparValor.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        BtnLimparValor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/broom_24px.png"))); // NOI18N
        BtnLimparValor.setText("Limpar Valor");
        BtnLimparValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimparValorActionPerformed(evt);
            }
        });

        BtnLimparValor1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        BtnLimparValor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/cancel_2_24px.png"))); // NOI18N
        BtnLimparValor1.setText("Cancelar");
        BtnLimparValor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimparValor1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(BtnLimparValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(BtnLimparValor1)
                        .addGap(18, 18, 18)
                        .addComponent(BtnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(66, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnOK)
                    .addComponent(BtnLimparValor1)
                    .addComponent(BtnLimparValor))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtValorRecebidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtValorRecebidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtValorRecebidoActionPerformed

    private void BtnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOKActionPerformed
        desconto = Double.parseDouble(Txtdesconto.getText());
        valorRecebido = Double.parseDouble(TxtValorRecebido.getText());
        formaPag = (String) CBPagamento.getSelectedItem();
        troco = Double.parseDouble(LbTroco.getText());
        subtotal = Double.parseDouble(TxtSubtotal.getText());
        this.pago = true;
        this.dispose();
    }//GEN-LAST:event_BtnOKActionPerformed

    private void TxtdescontoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtdescontoFocusLost
        calcularPagamento();
    }//GEN-LAST:event_TxtdescontoFocusLost

    private void TxtValorRecebidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtValorRecebidoFocusLost
        if (TxtValorRecebido.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Você deve Inserir o valor entregue pelo cliente", "Atenção", JOptionPane.WARNING_MESSAGE);
            TxtValorRecebido.requestFocus();

        } else {
            if (Double.parseDouble(TxtValorRecebido.getText()) < (Double.parseDouble(TxtSubtotal.getText()) - Double.parseDouble(Txtdesconto.getText()))) {
                JOptionPane.showMessageDialog(this, "Valor Recebido não corresponde ao valor a pagar", "Atenção", JOptionPane.WARNING_MESSAGE);
            } else {
                calcularPagamento();
            }
        }
    }//GEN-LAST:event_TxtValorRecebidoFocusLost

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.pago = false;
    }//GEN-LAST:event_formWindowClosed

    private void TxtValorRecebidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtValorRecebidoKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            if (TxtValorRecebido.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Você deve Inserir o valor entregue pelo cliente", "Atenção", JOptionPane.WARNING_MESSAGE);
                TxtValorRecebido.requestFocus();

            } else {
                if (Double.parseDouble(TxtValorRecebido.getText()) < (Double.parseDouble(TxtSubtotal.getText()) - Double.parseDouble(Txtdesconto.getText()))) {
                    JOptionPane.showMessageDialog(this, "Valor Recebido não corresponde ao valor a pagar", "Atenção", JOptionPane.WARNING_MESSAGE);
                } else {
                    calcularPagamento();
                }
            }
        }
    }//GEN-LAST:event_TxtValorRecebidoKeyPressed

    private void CbNomeCliPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_CbNomeCliPopupMenuWillBecomeInvisible
        if (CbNomeCli.isPopupVisible()) {
            carregarComboCliente();
            CbNomeCli.setPopupVisible(false);
        }
    }//GEN-LAST:event_CbNomeCliPopupMenuWillBecomeInvisible

    private void CbNomeCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbNomeCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbNomeCliActionPerformed

    private void BtnLimparValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimparValorActionPerformed
       TxtValorRecebido.setText("");
    }//GEN-LAST:event_BtnLimparValorActionPerformed

    private void BtnCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCincoActionPerformed
      valor=5;
      TxtValorRecebido.setText(""+(Integer.parseInt(TxtValorRecebido.getText())+valor));
    }//GEN-LAST:event_BtnCincoActionPerformed

    private void BtnDezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDezActionPerformed
      valor=10;
      TxtValorRecebido.setText(""+(Integer.parseInt(TxtValorRecebido.getText())+valor));
    }//GEN-LAST:event_BtnDezActionPerformed

    private void BtnCinquentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCinquentaActionPerformed
      valor=50;
      TxtValorRecebido.setText(""+(Integer.parseInt(TxtValorRecebido.getText())+valor));
    }//GEN-LAST:event_BtnCinquentaActionPerformed

    private void BtnCemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCemActionPerformed
      valor=100;
      TxtValorRecebido.setText(""+(Integer.parseInt(TxtValorRecebido.getText())+valor));
    }//GEN-LAST:event_BtnCemActionPerformed

    private void BtnQuinhentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnQuinhentoActionPerformed
        valor=500;
      TxtValorRecebido.setText(""+(Integer.parseInt(TxtValorRecebido.getText())+valor));
    }//GEN-LAST:event_BtnQuinhentoActionPerformed

    private void BtnMilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMilActionPerformed
      valor=1000;
      TxtValorRecebido.setText(""+(Integer.parseInt(TxtValorRecebido.getText())+valor));
    }//GEN-LAST:event_BtnMilActionPerformed

    private void BtnDoismilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDoismilActionPerformed
       valor=2000;
      TxtValorRecebido.setText(""+(Integer.parseInt(TxtValorRecebido.getText())+valor));
    }//GEN-LAST:event_BtnDoismilActionPerformed

    private void BtnCincomilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCincomilActionPerformed
      valor=5000;
      TxtValorRecebido.setText(""+(Integer.parseInt(TxtValorRecebido.getText())+valor));
    }//GEN-LAST:event_BtnCincomilActionPerformed

    private void BtnLimparValor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimparValor1ActionPerformed
      this.pago = false;
      dispose();
    }//GEN-LAST:event_BtnLimparValor1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPagamentoPDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPagamentoPDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPagamentoPDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPagamentoPDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewPagamentoPDV dialog = new ViewPagamentoPDV(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCem;
    private javax.swing.JButton BtnCinco;
    private javax.swing.JButton BtnCincomil;
    private javax.swing.JButton BtnCinquenta;
    private javax.swing.JButton BtnDez;
    private javax.swing.JButton BtnDoismil;
    private javax.swing.JButton BtnLimparValor;
    private javax.swing.JButton BtnLimparValor1;
    private javax.swing.JButton BtnMil;
    private javax.swing.JButton BtnOK;
    private javax.swing.JButton BtnQuinhento;
    private javax.swing.JComboBox<String> CBPagamento;
    private componentes.UJComboBox CbNomeCli;
    public javax.swing.JLabel LbTotal;
    private javax.swing.JLabel LbTroco;
    private javax.swing.JFormattedTextField TxtSubtotal;
    private javax.swing.JFormattedTextField TxtValorRecebido;
    private javax.swing.JFormattedTextField Txtdesconto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables

    private void listarCliente() {
        listaCliente = cc.listaClienteControllerCliente("");
        CbNomeCli.removeAllItems();
        for (int i = 0; i < listaCliente.size(); i++) {
            CbNomeCli.addItem(listaCliente.get(i).getCliNome());

        }
    }

    public void carregarComboCliente() {
        mdc = cc.listarClienteNome(CbNomeCli.getSelectedItem().toString());
        CodCLi = mdc.getIdCliente();
    }

    private void calcularPagamento() {
        double desco, subto, pagar, receber = 0, trocos;
        subto = Double.parseDouble(TxtSubtotal.getText());
        if (!Txtdesconto.getText().equals("")) {
            desco = Double.parseDouble(Txtdesconto.getText());
        } else {
            desco = 0;
        }
        if (!TxtValorRecebido.getText().equals("")) {
            receber = Double.parseDouble(TxtValorRecebido.getText());
        } else {
            TxtValorRecebido.requestFocus();
        }
        pagar = subto - desco;
        LbTotal.setText(pagar + "");

        trocos = receber - pagar;
        LbTroco.setText(trocos + "");
    }

    private void listarFormaPagamento() {
        listaMFP = CFP.listaControllerFormaPagamento("");
        CBPagamento.removeAllItems();
        for (int i = 0; i < listaMFP.size(); i++) {
            CBPagamento.addItem(listaMFP.get(i).getDescripag());

        }
    }

    public void setarValorTxt() {
        this.TxtSubtotal.setText("" + subtotal);
    }

    public double getSubtotal() {
        return subtotal;
    }

    public void setSubtotal(double subtotal) {
        this.subtotal = subtotal;
    }

    public double getDesconto() {
        return desconto;
    }

    public void setDesconto(double desconto) {
        this.desconto = desconto;
    }

    public double getValorRecebido() {
        return valorRecebido;
    }

    public void setValorRecebido(double valorRecebido) {
        this.valorRecebido = valorRecebido;
    }

    public double getTroco() {
        return troco;
    }

    public void setTroco(double troco) {
        this.troco = troco;
    }

    public String getFormaPag() {
        return formaPag;
    }

    public void setFormaPag(String formaPag) {
        this.formaPag = formaPag;
    }

    public boolean isPago() {
        return pago;
    }

    public void setPago(boolean pago) {
        this.pago = pago;
    }

}
