/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerItensVenda;
import controller.ControllerProduto;
import controller.ControllerVenda;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.print.DocFlavor;
import javax.print.DocPrintJob;
import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import javax.print.SimpleDoc;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.print.attribute.standard.JobName;
import javax.print.attribute.standard.MediaSizeName;
import javax.print.attribute.standard.OrientationRequested;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ModelItensVenda;
import model.ModelItensVendaProduto;
import model.ModelProduto;
import model.ModelSessaoUsuario;
import model.ModelVenda;
import utilitario.ViewUtili;

/**
 *
 * @author AurelioTEC
 */
public class ViewPDV extends javax.swing.JFrame {

    ControllerProduto cp = new ControllerProduto();
    ControllerItensVenda civ = new ControllerItensVenda();
    ControllerVenda cv = new ControllerVenda();
    ModelProduto mp = new ModelProduto();
    ModelVenda mv = new ModelVenda();
    ModelItensVenda miv = new ModelItensVenda();
    ModelSessaoUsuario msu = new ModelSessaoUsuario();
    ArrayList<ModelItensVenda> listaIV = new ArrayList<>();
    ArrayList<ModelProduto> listaProduto = new ArrayList<>();
    ArrayList<ModelItensVendaProduto> listaIVP = new ArrayList<>();

    private final ViewPagamentoPDV vPagPDV;
    int qtd = 1, CodCli;
    int Codvenda=0;
    /**
     * Creates new form ViewPDV
     */
    public ViewPDV() {
        initComponents();
        LbOperador.setText(msu.nomeusu);
        LbEstado.setText(msu.estado);
        this.vPagPDV = new ViewPagamentoPDV(this, true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LbCaixa = new javax.swing.JLabel();
        LbOperador = new javax.swing.JLabel();
        LbEstado = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        LbBruto = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        LbAtalho = new javax.swing.JLabel();
        LbAtalho1 = new javax.swing.JLabel();
        LbAtalho2 = new javax.swing.JLabel();
        LbAtalho3 = new javax.swing.JLabel();
        LbAtalho4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbItens = new javax.swing.JTable();
        TxtCodigo = new javax.swing.JFormattedTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MnAlterarQtd = new javax.swing.JMenuItem();
        MnFinalizarVenda = new javax.swing.JMenuItem();
        MnPesquisar = new javax.swing.JMenuItem();
        MnRemover = new javax.swing.JMenuItem();
        MnCancelarVenda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(215, 55));
        setPreferredSize(new java.awt.Dimension(1140, 655));

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SISTEMA DE GESTÃO COMERCIAL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255,80));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("OPERADOR:");

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("CAIXA: ");

        LbCaixa.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        LbCaixa.setForeground(new java.awt.Color(204, 204, 204));

        LbOperador.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        LbOperador.setForeground(new java.awt.Color(204, 204, 204));

        LbEstado.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        LbEstado.setForeground(new java.awt.Color(204, 204, 204));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("ESTADO:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LbCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(LbOperador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LbEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LbCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LbOperador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(LbEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255,80));

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("VALOR BRUTO");

        LbBruto.setBackground(new java.awt.Color(80, 80, 115));
        LbBruto.setFont(new java.awt.Font("sansserif", 1, 22)); // NOI18N
        LbBruto.setForeground(new java.awt.Color(204, 204, 204));
        LbBruto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbBruto.setOpaque(true);

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("TECLAS DE ATALHO");

        LbAtalho.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        LbAtalho.setForeground(new java.awt.Color(204, 204, 204));
        LbAtalho.setText("F3 - Alterar a Qtd do produto");

        LbAtalho1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        LbAtalho1.setForeground(new java.awt.Color(204, 204, 204));
        LbAtalho1.setText("F4 - Finalizar a venda");

        LbAtalho2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        LbAtalho2.setForeground(new java.awt.Color(204, 204, 204));
        LbAtalho2.setText("F5 - Procurar produto");

        LbAtalho3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        LbAtalho3.setForeground(new java.awt.Color(204, 204, 204));
        LbAtalho3.setText("Delete - Remover item da venda");

        LbAtalho4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        LbAtalho4.setForeground(new java.awt.Color(204, 204, 204));
        LbAtalho4.setText("Alt + F6 - Cancelar a venda");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LbBruto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(LbAtalho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LbAtalho1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LbAtalho2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LbAtalho3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LbAtalho4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(56, 56, 56))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LbBruto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(LbAtalho, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LbAtalho1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LbAtalho2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LbAtalho3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LbAtalho4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 51));

        TbItens.setBackground(new java.awt.Color(204, 204, 204));
        TbItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ITEM", "CODIGO", "NOME", "PREÇO", "QTD", "VALOR TOTAL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbItens.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jScrollPane1.setViewportView(TbItens);
        if (TbItens.getColumnModel().getColumnCount() > 0) {
            TbItens.getColumnModel().getColumn(0).setMinWidth(70);
            TbItens.getColumnModel().getColumn(0).setPreferredWidth(70);
            TbItens.getColumnModel().getColumn(0).setMaxWidth(70);
            TbItens.getColumnModel().getColumn(1).setMinWidth(100);
            TbItens.getColumnModel().getColumn(1).setPreferredWidth(100);
            TbItens.getColumnModel().getColumn(1).setMaxWidth(100);
            TbItens.getColumnModel().getColumn(2).setMinWidth(300);
            TbItens.getColumnModel().getColumn(2).setPreferredWidth(300);
            TbItens.getColumnModel().getColumn(3).setMinWidth(100);
            TbItens.getColumnModel().getColumn(3).setPreferredWidth(100);
            TbItens.getColumnModel().getColumn(4).setMinWidth(70);
            TbItens.getColumnModel().getColumn(4).setPreferredWidth(70);
            TbItens.getColumnModel().getColumn(4).setMaxWidth(70);
            TbItens.getColumnModel().getColumn(5).setMinWidth(100);
            TbItens.getColumnModel().getColumn(5).setPreferredWidth(100);
        }

        TxtCodigo.setBackground(new java.awt.Color(102, 102, 102));
        TxtCodigo.setForeground(new java.awt.Color(204, 204, 204));
        TxtCodigo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        TxtCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtCodigo.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        TxtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtCodigoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                    .addComponent(TxtCodigo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        jMenu1.setText("Arquivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/close_window_18px.png"))); // NOI18N
        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Atalhos");

        MnAlterarQtd.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        MnAlterarQtd.setText("Alterar Qtd");
        jMenu2.add(MnAlterarQtd);

        MnFinalizarVenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        MnFinalizarVenda.setText("Finalizar Venda");
        MnFinalizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnFinalizarVendaActionPerformed(evt);
            }
        });
        jMenu2.add(MnFinalizarVenda);

        MnPesquisar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        MnPesquisar.setText("Pesquisar Produto");
        MnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnPesquisarActionPerformed(evt);
            }
        });
        jMenu2.add(MnPesquisar);

        MnRemover.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, 0));
        MnRemover.setText("Remover Produto");
        MnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnRemoverActionPerformed(evt);
            }
        });
        jMenu2.add(MnRemover);

        MnCancelarVenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, java.awt.event.InputEvent.ALT_MASK));
        MnCancelarVenda.setText("Cancelar Venda");
        MnCancelarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnCancelarVendaActionPerformed(evt);
            }
        });
        jMenu2.add(MnCancelarVenda);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MnFinalizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnFinalizarVendaActionPerformed
        vPagPDV.setSubtotal(Double.parseDouble(LbBruto.getText()));
        vPagPDV.setarValorTxt();
        vPagPDV.setVisible(true);
       // LbDesconto.setText(vPagPDV.getDesconto() + "");
       // LbValorPagar.setText(vPagPDV.getSubtotal() + "");
        if (vPagPDV.isPago()) {
            salvarVenda();
            Codvenda = cv.getUltimaVendaController().getIdvenda();
           this.imprimirCupom();
           
        } else {
            JOptionPane.showMessageDialog(this, "Pagamento Cancelado", "Atenção", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_MnFinalizarVendaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void MnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnRemoverActionPerformed
        int qtdlinha = TbItens.getRowCount();
        if (qtdlinha < 1) {
            JOptionPane.showMessageDialog(this, "Não Existe itens para ser removido!", "Atenção", JOptionPane.WARNING_MESSAGE);
        } else {
            DefaultTableModel modelo = (DefaultTableModel) TbItens.getModel();
            int linha = Integer.parseInt(JOptionPane.showInputDialog(this, "Digita o Item a ser removido", "Informação", JOptionPane.OK_OPTION));
            int confirma = JOptionPane.showConfirmDialog(this, "Tem certesa que deseja remover o item: " + linha + " ?", "Atenção", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (confirma == JOptionPane.YES_OPTION) {
                modelo.removeRow(linha - 1);
                LbBruto.setText("" + somarTotal());
                for (int i = 0; i < qtdlinha; i++) {
                    modelo.setValueAt(i + 1, i, 0);
                }
            }
        }
    }//GEN-LAST:event_MnRemoverActionPerformed

    private void TxtCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCodigoKeyReleased
        pegarDados(evt);
    }//GEN-LAST:event_TxtCodigoKeyReleased

    private void MnCancelarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnCancelarVendaActionPerformed
        int confirma = JOptionPane.showConfirmDialog(this, "Tem certesa que deseja Cancelar a venda ?", "Atenção", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (confirma == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_MnCancelarVendaActionPerformed

    private void MnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnPesquisarActionPerformed
            JOptionPane.showMessageDialog(this, "Essa função ainda não foi implementada ", "Atenção", JOptionPane.INFORMATION_MESSAGE);
       
    }//GEN-LAST:event_MnPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPDV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbAtalho;
    private javax.swing.JLabel LbAtalho1;
    private javax.swing.JLabel LbAtalho2;
    private javax.swing.JLabel LbAtalho3;
    private javax.swing.JLabel LbAtalho4;
    private javax.swing.JLabel LbBruto;
    private javax.swing.JLabel LbCaixa;
    private javax.swing.JLabel LbEstado;
    private javax.swing.JLabel LbOperador;
    private javax.swing.JMenuItem MnAlterarQtd;
    private javax.swing.JMenuItem MnCancelarVenda;
    private javax.swing.JMenuItem MnFinalizarVenda;
    private javax.swing.JMenuItem MnPesquisar;
    private javax.swing.JMenuItem MnRemover;
    private javax.swing.JTable TbItens;
    private javax.swing.JFormattedTextField TxtCodigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void salvarVenda() {
        int codigoVenda = 0;
        mv = new ModelVenda();
        mv.setIdcliente(CodCli=vPagPDV.CodCLi);
        mv.setDesconto(vPagPDV.getDesconto());
        mv.setValor(vPagPDV.getSubtotal());
        mv.setValortotal(Double.parseDouble(vPagPDV.LbTotal.getText()));

        codigoVenda = cv.salvarvendaController(mv);
        int cont = TbItens.getRowCount();

        for (int i = 0; i < cont; i++) {
            int codigoP = (int) TbItens.getValueAt(i, 1);
            miv = new ModelItensVenda();
            mp = new ModelProduto();
            miv.setCodproduto(codigoP);
            miv.setCodvenda(codigoVenda);
            miv.setItensvalor((double) TbItens.getValueAt(i, 3));
            miv.setIntensqtd(Integer.parseInt(TbItens.getValueAt(i, 4).toString()));

            //Produto
            mp.setIdProduto((int) TbItens.getValueAt(i, 1));
            mp.setProEstoque(cp.listarProduto(codigoP).getProEstoque() - Integer.parseInt(TbItens.getValueAt(i, 4).toString()));
            listaIV.add(miv);
            listaProduto.add(mp);

        }
        if (civ.salvarItensVendaController(listaIV)) {
            cp.alterarEstoqueProdutoController(listaProduto);
            JOptionPane.showMessageDialog(this, "Venda Efetuada com Sucesso!", "Informação", JOptionPane.INFORMATION_MESSAGE);
            this.limpar();

        } else {
            JOptionPane.showMessageDialog(this, "Venda Não Efetuada!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    private double somarTotal() {
        double soma = 0, valor = 0;
        int cont = TbItens.getRowCount();
        for (int i = 0; i < cont; i++) {
            valor = Double.parseDouble(String.valueOf(TbItens.getValueAt(i, 5)));
            soma += valor;
        }

        return soma;
    }

    private void pegarDados(java.awt.event.KeyEvent evt) {
        DefaultTableModel modelo = (DefaultTableModel) TbItens.getModel();
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            try {
                if (!TxtCodigo.getText().equals("")) {
                    String qtda = JOptionPane.showInputDialog(this, "Digita a Quantidade", "Informação", JOptionPane.OK_OPTION);
                    mp = cp.listarProduto(Integer.parseInt(TxtCodigo.getText()));
                    modelo.addRow(new Object[]{
                        modelo.getRowCount() + 1,
                        mp.getIdProduto(),
                        mp.getProNome(),
                        mp.getProValor(),
                        qtd = Integer.parseInt(qtda),
                        mp.getProValor() * qtd
                    });
                    LbBruto.setText("" + somarTotal());
                    TxtCodigo.setText("");
                } else {
                    JOptionPane.showMessageDialog(this, "Voce deve informar o codigo do produto", "Informação", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (Exception e) {

            }
        }

    }

    private void limpar() {
        DefaultTableModel modelo = (DefaultTableModel) TbItens.getModel();
        modelo.setNumRows(0);
        LbBruto.setText("");
       // LbDesconto.setText("");
       // LbValorPagar.setText("");
    }

    private void imprimirCupomController(ArrayList<ModelItensVendaProduto> listaMIVP, ModelVenda mv) {
       String formatoData="dd/MM/yyyy";
       String formatoHora="HH:mm";
       String data,hora;
       Date tempoAtual= new Date();
       SimpleDateFormat formata= new SimpleDateFormat(formatoData);
       data= formata.format(tempoAtual);
       formata= new SimpleDateFormat(formatoHora);
       hora= formata.format(tempoAtual);
       
       String conteudoImprimir="";
        for (int i = 0; i < listaMIVP.size(); i++) {
            
            conteudoImprimir += listaMIVP.get(i).getMprodutos().getIdProduto()+"  "+listaMIVP.get(i).getMprodutos().getProNome()+"  "+listaMIVP.get(i).getmItensVenda().getIntensqtd()+"  "+listaMIVP.get(i).getmItensVenda().getItensvalor()+"\n\r";
        }
        this.imprimir("SISTEMA DE GESTÃO COMERCIAL \n\r"
                    + "----------------------------\n\r"
                    + "           FATURA           \n\r"
                    + "----------------------------\n\r"
                    + "COD  DESC   QTD  PREÇO \n\r"
                    +  conteudoImprimir+""
                    + "----------------------------\n\r"
                    + " VALOR BRUTO: "+mv.getValor()+"\n\r"
                    + " DESCONTO: "+mv.getDesconto()+"\n\r"
                    + " TOTAL GERAL: "+mv.getValortotal()+"\n\r"
                    + "----------------------------\n\r"
                    + " DATA: data      HORA: hora \n\r"
                    + "    OBRIGADO VOLTA SEMPRE   \n\r"             
                    + "\n\r\f" 
        );
        
    }
 
    public void imprimir(String texto){
        try {
            InputStream print= new ByteArrayInputStream(texto.getBytes());
            DocFlavor doflavor=DocFlavor.INPUT_STREAM.AUTOSENSE;
            SimpleDoc doctexto= new SimpleDoc(print, doflavor, null);
            PrintService ps= PrintServiceLookup.lookupDefaultPrintService();
            
            PrintRequestAttributeSet pa= new HashPrintRequestAttributeSet();
            pa.add(new JobName("Impressão", null));
            pa.add(OrientationRequested.PORTRAIT);
            pa.add(MediaSizeName.ISO_A4);
            
            DocPrintJob docpj=ps.createPrintJob();
            try {
                docpj.print(doctexto, pa);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Não foi possivel imprimir", "Erro", JOptionPane.ERROR_MESSAGE);
            }
            print.close();
            
        } catch (Exception e) {
        }
        
    }
    private void imprimirCupom(){      
        final ViewUtili vu= new ViewUtili();
        vu.setVisible(true);
        Thread tr=new Thread(){
            public void run(){
                try {
                    cv.imprimirRelvendasControoller(Codvenda);
                    vu.dispose();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Erro ao Gerar o Relatório! \n" + e, "Erro", JOptionPane.ERROR_MESSAGE);
                }
                
            }
        };
        tr.start();
    }

}
