package view;

import controller.ControllerConfig;
import java.io.File;
import java.io.FileWriter;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author AurelioTEC
 */
public class ViewConfig extends javax.swing.JFrame {

    ControllerConfig config = new ControllerConfig();
    ArrayList<String> tabelas = new ArrayList<>();
    String pasta = null;
    String nomeFicheiro;
    int opcao;

    /**
     * Creates new form ViewConfig
     */
    public ViewConfig() {
        initComponents();
        this.setLocationRelativeTo(null);
        //this.carregarTabelas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TPnConfig = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        TxtCaminhoBack = new javax.swing.JTextField();
        BtnselectPastaBack = new javax.swing.JButton();
        BtnAplicarBack = new javax.swing.JButton();
        BtnCancelarBack = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        TxtCaminhoRest = new javax.swing.JTextField();
        BtnselectPastaRest = new javax.swing.JButton();
        BtnAplicarRestore = new javax.swing.JButton();
        BtnCancelarRest = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        CHBLimpaVenda = new javax.swing.JCheckBox();
        CHBLimparPoduto = new javax.swing.JCheckBox();
        CHBLimparCliente = new javax.swing.JCheckBox();
        CHBLimparItvendas = new javax.swing.JCheckBox();
        BtnSelecionarTudo = new javax.swing.JButton();
        BtnAplicar1 = new javax.swing.JButton();
        BtnCancelar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configurações");
        setResizable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 202, Short.MAX_VALUE)
        );

        TPnConfig.addTab("Mudar Tema", jPanel2);

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TxtCaminhoBack.setEditable(false);

        BtnselectPastaBack.setText("Selecionar Pasta");
        BtnselectPastaBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnselectPastaBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(TxtCaminhoBack, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnselectPastaBack, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtCaminhoBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnselectPastaBack))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        BtnAplicarBack.setText("Aplicar");
        BtnAplicarBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAplicarBackActionPerformed(evt);
            }
        });

        BtnCancelarBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/cancel_18px.png"))); // NOI18N
        BtnCancelarBack.setText("Cancelar");
        BtnCancelarBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtnAplicarBack, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnCancelarBack, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAplicarBack)
                    .addComponent(BtnCancelarBack))
                .addGap(0, 23, Short.MAX_VALUE))
        );

        TPnConfig.addTab("Backup do Banco", jPanel4);

        jPanel5.setBorder(null);

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TxtCaminhoRest.setEditable(false);

        BtnselectPastaRest.setText("Buscar Arquivo");
        BtnselectPastaRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnselectPastaRestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(TxtCaminhoRest, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnselectPastaRest, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtCaminhoRest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnselectPastaRest))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        BtnAplicarRestore.setText("Aplicar");
        BtnAplicarRestore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAplicarRestoreActionPerformed(evt);
            }
        });

        BtnCancelarRest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/cancel_18px.png"))); // NOI18N
        BtnCancelarRest.setText("Cancelar");
        BtnCancelarRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarRestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtnAplicarRestore, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnCancelarRest, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAplicarRestore)
                    .addComponent(BtnCancelarRest))
                .addGap(0, 23, Short.MAX_VALUE))
        );

        TPnConfig.addTab("Restaurar Banco", jPanel5);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Selecionar Item a Limpar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("sansserif", 1, 18))); // NOI18N

        CHBLimpaVenda.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        CHBLimpaVenda.setText("Limpar Venda");
        CHBLimpaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHBLimpaVendaActionPerformed(evt);
            }
        });

        CHBLimparPoduto.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        CHBLimparPoduto.setText("Limpar Produto");

        CHBLimparCliente.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        CHBLimparCliente.setText("Limpar Clientes");

        CHBLimparItvendas.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        CHBLimparItvendas.setText("Limpar Itens da Venda");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CHBLimpaVenda)
                    .addComponent(CHBLimparCliente))
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CHBLimparPoduto)
                    .addComponent(CHBLimparItvendas))
                .addGap(0, 41, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CHBLimpaVenda)
                    .addComponent(CHBLimparPoduto))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CHBLimparCliente)
                    .addComponent(CHBLimparItvendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        BtnSelecionarTudo.setText("Selecionar Tudo");

        BtnAplicar1.setText("Aplicar");

        BtnCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/cancel_18px.png"))); // NOI18N
        BtnCancelar1.setText("Cancelar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(BtnSelecionarTudo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnAplicar1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSelecionarTudo)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BtnAplicar1)
                        .addComponent(BtnCancelar1)))
                .addGap(41, 41, 41))
        );

        TPnConfig.addTab("Limpar Banco", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TPnConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TPnConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CHBLimpaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHBLimpaVendaActionPerformed

    }//GEN-LAST:event_CHBLimpaVendaActionPerformed

    private void BtnselectPastaBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnselectPastaBackActionPerformed
        JFileChooser fc = new JFileChooser();
        int result = fc.showSaveDialog(this);
        String data = new SimpleDateFormat("yyyy-MM-dd").format(new Date());
        if (result == JFileChooser.APPROVE_OPTION) {
            File f = fc.getSelectedFile();
            try {
                pasta = f.getAbsolutePath();
                pasta = pasta.replace("\\", "/");
                pasta = pasta + "_" + data + ".sql";
                TxtCaminhoBack.setText(pasta);
                if (f.exists()) {
                    Object[] options = {"Sim", "Não"};
                    opcao = JOptionPane.showOptionDialog(this, "Este ficheiro ja existe deseja subscrever o ficheiro", "Informação", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
                    if (opcao == JOptionPane.YES_NO_OPTION) {
                        f.createNewFile();
                        pasta = f.getAbsolutePath();
                        pasta = pasta.replace("\\", "/");
                        pasta = pasta + "_" + data + ".sql";
                        TxtCaminhoBack.setText(pasta);

                    }
                }

            } catch (Exception e) {
                e.printStackTrace();
            }

        }


    }//GEN-LAST:event_BtnselectPastaBackActionPerformed

    private void BtnAplicarBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAplicarBackActionPerformed

        Process p = null;
        try {
            Runtime run = Runtime.getRuntime();
            p = run.exec("C:\\xampp\\mysql\\bin\\mysqldump.exe -v -v -v --host=localhost --user=root --port=3306 --protocol=tcp --force --allow-keywords --compress --add-drop-table --result-file=" + pasta + " --databases lojita");
            int processoCompleto = p.waitFor();
            if (processoCompleto == 0) {
                JOptionPane.showMessageDialog(this, "Backup efetuado com sucesso", "Informação", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Backup não foi efetuado", "Atenção", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Backup não foi efetuado " + e, "Atenção", JOptionPane.WARNING_MESSAGE);
            //e.printStackTrace();
        }
    }//GEN-LAST:event_BtnAplicarBackActionPerformed

    private void BtnselectPastaRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnselectPastaRestActionPerformed
        JFileChooser fc = new JFileChooser();
        int result = fc.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File f = fc.getSelectedFile();
            try {
                pasta = f.getAbsolutePath();
                pasta = pasta.replace("\\", "/");
                TxtCaminhoRest.setText(pasta);
            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_BtnselectPastaRestActionPerformed

    private void BtnAplicarRestoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAplicarRestoreActionPerformed
      String[] rest= new String[]{"C:\\xampp\\mysql\\bin\\mysql.exe", " --host=localhost --user=root -e", "source "+pasta};
       Process p;
        try {
         p = Runtime.getRuntime().exec(rest);
         int processoCompleto = p.waitFor();
            if (processoCompleto == 0) {
                JOptionPane.showMessageDialog(this, "Restauro efetuado com sucesso", "Informação", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Restauro não foi efetuado", "Atenção", JOptionPane.WARNING_MESSAGE);
            }
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_BtnAplicarRestoreActionPerformed

    private void BtnCancelarBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarBackActionPerformed
        TxtCaminhoBack.setText("");
    }//GEN-LAST:event_BtnCancelarBackActionPerformed

    private void BtnCancelarRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarRestActionPerformed
     TxtCaminhoRest.setText("");
    }//GEN-LAST:event_BtnCancelarRestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewConfig().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAplicar1;
    private javax.swing.JButton BtnAplicarBack;
    private javax.swing.JButton BtnAplicarRestore;
    private javax.swing.JButton BtnCancelar1;
    private javax.swing.JButton BtnCancelarBack;
    private javax.swing.JButton BtnCancelarRest;
    private javax.swing.JButton BtnSelecionarTudo;
    private javax.swing.JButton BtnselectPastaBack;
    private javax.swing.JButton BtnselectPastaRest;
    private javax.swing.JCheckBox CHBLimpaVenda;
    private javax.swing.JCheckBox CHBLimparCliente;
    private javax.swing.JCheckBox CHBLimparItvendas;
    private javax.swing.JCheckBox CHBLimparPoduto;
    private javax.swing.JTabbedPane TPnConfig;
    private javax.swing.JTextField TxtCaminhoBack;
    private javax.swing.JTextField TxtCaminhoRest;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables

    /*private void carregarTabelas(){
    tabelas= config.mostrarTabelaController();
    cbTabelas.removeAllItems();
    for (int i = 0; i < tabelas.size(); i++) {
      cbTabelas.addItem(tabelas.get(i));
    }
        
    }*/
}
