/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.Timer;
import model.ModelSessaoUsuario;

/**
 *
 * @author AurelioTEC
 */
public class ViewPrincipal extends javax.swing.JFrame {

    ModelSessaoUsuario msu = new ModelSessaoUsuario();

    /**
     * Creates new form ViewPrincipal
     */
    public ViewPrincipal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        Date data = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        LbData.setText(formato.format(data));
        Timer tempo = new Timer(1000, new hora());
        tempo.start();
        LbUsuario.setText(msu.nomeusu);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        uJPanelImagem1 = new componentes.UJPanelImagem();
        jPanel2 = new javax.swing.JPanel();
        BtnCliente = new javax.swing.JButton();
        BtnProduto = new javax.swing.JButton();
        BtnVenda = new javax.swing.JButton();
        BtnUsuario = new javax.swing.JButton();
        BtnPDV = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LbUsuario = new javax.swing.JLabel();
        LbData = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LbHora = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MnuArquivo = new javax.swing.JMenu();
        MnSair = new javax.swing.JMenuItem();
        MnuCadastro = new javax.swing.JMenu();
        MnClientes = new javax.swing.JMenuItem();
        MnProdutos = new javax.swing.JMenuItem();
        MnUsuarios = new javax.swing.JMenuItem();
        MnuRelatorio = new javax.swing.JMenu();
        MnRelClientes = new javax.swing.JMenuItem();
        MnRelProdutos = new javax.swing.JMenuItem();
        MnrelUsuarios = new javax.swing.JMenuItem();
        MnRelVendas = new javax.swing.JMenuItem();
        MnuVenda = new javax.swing.JMenu();
        MnVenda = new javax.swing.JMenuItem();
        MnPDV = new javax.swing.JMenuItem();
        MnuOpcao = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gestão Comercial");
        setResizable(false);

        uJPanelImagem1.setImagem(new java.io.File("C:\\Users\\AurelioTEC\\Documents\\NetBeansProjects\\Lojita\\src\\imagens\\24x24\\Background1.jpg"));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153, 80));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 543));

        BtnCliente.setBackground(new java.awt.Color(18, 30, 49, 60));
        BtnCliente.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        BtnCliente.setForeground(new java.awt.Color(255, 255, 255));
        BtnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/commercial_development_managementW_40px.png"))); // NOI18N
        BtnCliente.setText("Clientes");
        BtnCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClienteActionPerformed(evt);
            }
        });

        BtnProduto.setBackground(new java.awt.Color(18, 30, 49, 60));
        BtnProduto.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        BtnProduto.setForeground(new java.awt.Color(255, 255, 255));
        BtnProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/productW_40px.png"))); // NOI18N
        BtnProduto.setText("Produtos");
        BtnProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProdutoActionPerformed(evt);
            }
        });

        BtnVenda.setBackground(new java.awt.Color(18, 30, 49, 60));
        BtnVenda.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        BtnVenda.setForeground(new java.awt.Color(255, 255, 255));
        BtnVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/cash_registerW_40px.png"))); // NOI18N
        BtnVenda.setText("Vendas");
        BtnVenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVendaActionPerformed(evt);
            }
        });

        BtnUsuario.setBackground(new java.awt.Color(18, 30, 49, 60));
        BtnUsuario.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        BtnUsuario.setForeground(new java.awt.Color(255, 255, 255));
        BtnUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/conference_background_selectedW_40px.png"))); // NOI18N
        BtnUsuario.setText("Usuarios");
        BtnUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUsuarioActionPerformed(evt);
            }
        });

        BtnPDV.setBackground(new java.awt.Color(18, 30, 49, 60));
        BtnPDV.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        BtnPDV.setForeground(new java.awt.Color(255, 255, 255));
        BtnPDV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/old_cash_registerW_40px.png"))); // NOI18N
        BtnPDV.setText("Ponto de Venda");
        BtnPDV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnPDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPDVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnPDV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(BtnCliente)
                .addGap(18, 18, 18)
                .addComponent(BtnProduto)
                .addGap(18, 18, 18)
                .addComponent(BtnVenda)
                .addGap(18, 18, 18)
                .addComponent(BtnUsuario)
                .addGap(18, 18, 18)
                .addComponent(BtnPDV)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 153, 80));
        jPanel3.setFocusCycleRoot(true);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/user_18px.png"))); // NOI18N
        jLabel1.setText("Usuario Logado:");

        LbUsuario.setBackground(new java.awt.Color(128, 128, 128,80));
        LbUsuario.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        LbUsuario.setForeground(new java.awt.Color(255, 255, 255));

        LbData.setBackground(new java.awt.Color(128, 128, 128,80));
        LbData.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        LbData.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/calendar_18px.png"))); // NOI18N
        jLabel2.setText("Data:");

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/clock_18px.png"))); // NOI18N
        jLabel3.setText("Hora :");

        LbHora.setBackground(new java.awt.Color(48, 103, 165));
        LbHora.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        LbHora.setForeground(new java.awt.Color(255, 255, 255));
        LbHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbHora.setOpaque(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LbData, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LbHora, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(LbHora, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LbData, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LbUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout uJPanelImagem1Layout = new javax.swing.GroupLayout(uJPanelImagem1);
        uJPanelImagem1.setLayout(uJPanelImagem1Layout);
        uJPanelImagem1Layout.setHorizontalGroup(
            uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        uJPanelImagem1Layout.setVerticalGroup(
            uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, uJPanelImagem1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(uJPanelImagem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(uJPanelImagem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        MnuArquivo.setText("Arquivo");

        MnSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        MnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/close_window_18px.png"))); // NOI18N
        MnSair.setText("Sair");
        MnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnSairActionPerformed(evt);
            }
        });
        MnuArquivo.add(MnSair);

        jMenuBar1.add(MnuArquivo);

        MnuCadastro.setText("Cadastro");

        MnClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        MnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/add_user_group_man_man_18px.png"))); // NOI18N
        MnClientes.setText("Clientes");
        MnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnClientesActionPerformed(evt);
            }
        });
        MnuCadastro.add(MnClientes);

        MnProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        MnProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/product_18px.png"))); // NOI18N
        MnProdutos.setText("Produtos");
        MnProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnProdutosActionPerformed(evt);
            }
        });
        MnuCadastro.add(MnProdutos);

        MnUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        MnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/commercial_development_management_18px.png"))); // NOI18N
        MnUsuarios.setText("Usuarios");
        MnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnUsuariosActionPerformed(evt);
            }
        });
        MnuCadastro.add(MnUsuarios);

        jMenuBar1.add(MnuCadastro);

        MnuRelatorio.setText("Relatorio");

        MnRelClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MnRelClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/conference_18px.png"))); // NOI18N
        MnRelClientes.setText("Clientes");
        MnuRelatorio.add(MnRelClientes);

        MnRelProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MnRelProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/send_job_list_18px.png"))); // NOI18N
        MnRelProdutos.setText("Produtos");
        MnRelProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnRelProdutosActionPerformed(evt);
            }
        });
        MnuRelatorio.add(MnRelProdutos);

        MnrelUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MnrelUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/overview_pages_1_18px.png"))); // NOI18N
        MnrelUsuarios.setText("Usuarios");
        MnrelUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnrelUsuariosActionPerformed(evt);
            }
        });
        MnuRelatorio.add(MnrelUsuarios);

        MnRelVendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MnRelVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/todo_list_18px.png"))); // NOI18N
        MnRelVendas.setText("Vendas");
        MnuRelatorio.add(MnRelVendas);

        jMenuBar1.add(MnuRelatorio);

        MnuVenda.setText("Vendas");

        MnVenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        MnVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/checkout_18px.png"))); // NOI18N
        MnVenda.setText("Vender");
        MnVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnVendaActionPerformed(evt);
            }
        });
        MnuVenda.add(MnVenda);

        MnPDV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.ALT_MASK));
        MnPDV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/cash_register_18px.png"))); // NOI18N
        MnPDV.setText("PDV");
        MnPDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnPDVActionPerformed(evt);
            }
        });
        MnuVenda.add(MnPDV);

        jMenuBar1.add(MnuVenda);

        MnuOpcao.setText("Opções");
        MnuOpcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuOpcaoActionPerformed(evt);
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/info_18px.png"))); // NOI18N
        jMenuItem1.setText("Info.");
        MnuOpcao.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F11, 0));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/help_18px.png"))); // NOI18N
        jMenuItem2.setText("Ajuda");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        MnuOpcao.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/services_18px.png"))); // NOI18N
        jMenuItem3.setText("Configurar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        MnuOpcao.add(jMenuItem3);

        jMenuBar1.add(MnuOpcao);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_MnSairActionPerformed

    private void MnProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnProdutosActionPerformed
        new ViewProduto().setVisible(true);
    }//GEN-LAST:event_MnProdutosActionPerformed

    private void MnRelProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnRelProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MnRelProdutosActionPerformed

    private void MnrelUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnrelUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MnrelUsuariosActionPerformed

    private void MnVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnVendaActionPerformed
        new ViewVenda().setVisible(true);
    }//GEN-LAST:event_MnVendaActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void MnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnClientesActionPerformed
        new ViewCliente().setVisible(true);
    }//GEN-LAST:event_MnClientesActionPerformed

    private void MnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnUsuariosActionPerformed
        new ViewUsuario().setVisible(true);
    }//GEN-LAST:event_MnUsuariosActionPerformed

    private void BtnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClienteActionPerformed
        new ViewCliente().setVisible(true);
    }//GEN-LAST:event_BtnClienteActionPerformed

    private void BtnProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProdutoActionPerformed
        new ViewProduto().setVisible(true);
    }//GEN-LAST:event_BtnProdutoActionPerformed

    private void BtnVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVendaActionPerformed
        new ViewVenda().setVisible(true);
    }//GEN-LAST:event_BtnVendaActionPerformed

    private void BtnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUsuarioActionPerformed
        new ViewUsuario().setVisible(true);
    }//GEN-LAST:event_BtnUsuarioActionPerformed

    private void BtnPDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPDVActionPerformed
        new ViewPDV().setVisible(true);
    }//GEN-LAST:event_BtnPDVActionPerformed

    private void MnuOpcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuOpcaoActionPerformed

    }//GEN-LAST:event_MnuOpcaoActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        new ViewConfig().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void MnPDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnPDVActionPerformed
        new ViewPDV().setVisible(true);
    }//GEN-LAST:event_MnPDVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCliente;
    private javax.swing.JButton BtnPDV;
    private javax.swing.JButton BtnProduto;
    private javax.swing.JButton BtnUsuario;
    private javax.swing.JButton BtnVenda;
    private javax.swing.JLabel LbData;
    private javax.swing.JLabel LbHora;
    private javax.swing.JLabel LbUsuario;
    private javax.swing.JMenuItem MnClientes;
    private javax.swing.JMenuItem MnPDV;
    private javax.swing.JMenuItem MnProdutos;
    private javax.swing.JMenuItem MnRelClientes;
    private javax.swing.JMenuItem MnRelProdutos;
    private javax.swing.JMenuItem MnRelVendas;
    private javax.swing.JMenuItem MnSair;
    private javax.swing.JMenuItem MnUsuarios;
    private javax.swing.JMenuItem MnVenda;
    private javax.swing.JMenuItem MnrelUsuarios;
    private javax.swing.JMenu MnuArquivo;
    private javax.swing.JMenu MnuCadastro;
    private javax.swing.JMenu MnuOpcao;
    private javax.swing.JMenu MnuRelatorio;
    private javax.swing.JMenu MnuVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private componentes.UJPanelImagem uJPanelImagem1;
    // End of variables declaration//GEN-END:variables
    class hora implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            Calendar now = Calendar.getInstance();
            LbHora.setText(String.format("%1$tH:%1$tM:%1$tS", now));

        }
    }
}
